### ISSUE TITLE
Theme option panels using Redux Framework don't work

### ISSUE THREAD

**Issue by rpharrison** [meitar/wp-sri#6]
With the plugin enabled, it is not possible to access my themes custom option panel, which is based on Redux Framework. Disabling your plugin immediately stops this behaviour.

Just a heads up in case anyone else sees this happening.

**Comment by meitar** [comment]
I'm not familiar with Redux Framework. (I assume you're talking about [this plugin](https://wordpress.org/plugins/redux-framework/)?) If there is an incompatibility my first suspicion is that Redux Framework tries to load assets by building some URLs whose response body content are different on each request. This would break Subresource Integrity by design. The solution would be to identify which URLs these are, and either manually or automatically add them to the exclusion list from this plugin. This can be done through runtime filters or by manually selection in this plugin's administration panel.

I also suggest you inform the Redux Framework authors of this incompatibility if you haven't done so already, as they are the ones who would be able to solve this for their users most easily.
